### ISSUE TITLE
@mention name in timeline post

### ISSUE THREAD

**Issue by rvnamb** [bootstrapguru/socialite-requests#47]
Currently the activity post only shows the name like ADMIN
It would be great if it shows something like ADMIN @bootstrapguru   so that users can easily find the @mention name without going into their profile to find the @mention name.
In twitter its like:  Admin @theadmin

**Comment by vijaythecoder** [comment]
its not possible like twitter, since there is no space if they add with friends and if his friend name is too long. I can add a tool tip when user hovers on name , then it will show the mention name
![image](https://cloud.githubusercontent.com/assets/1809727/18230415/19e9b1ce-72b8-11e6-97b0-4d4333526743.png)

**Comment by anusha65** [comment]
So here is how we impemented:
![image](https://cloud.githubusercontent.com/assets/5723954/18230444/593e9816-72b9-11e6-81f0-3c0d1fb08872.png)

**Comment by rvnamb** [comment]
It would be nice if you can show profile card when we hover on thw name. Then mention name can be seen on tge hover card. Just a suggestion to make the script more superb :)

**Comment by vijaythecoder** [comment]
yeah we are going to do it but not yet though , we still have lot of other requests :)

**Comment by rvnamb** [comment]
I will wait then :)
